language: java
jdk: openjdk11
branches:
  only:
    - develop
    - "/^release-[0-999].[0-999]/"
    - master
notifications:
  email:
    recipients:
      - brotherowsky@gmail.com
script:
  - mvn org.jacoco:jacoco-maven-plugin:prepare-agent verify
  - mvn sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=lconder -Dsonar.projectKey=lconder_iwvg-devops-luis-conde -Dsonar.login=$SONAR
deploy:
  provider: heroku
  api_key: $HEROKU
  app: iwvg-devops-luis-conde
  on:
    repo: lconder/iwvg-devops-luis-conde
    branch: master
  skip_cleanup: 'true'